databases:
  - name: rails_firebase_auth_database_2
    databaseName: rails_firebase_auth_database_2
    user: asami_takaoka
    region: singapore

services:
  - type: web
    name: rails-firebase-auth
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-firebase-auth
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

