# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %> # .env.productionにメモ
  database: <%= ENV["DATABASE"] %> # .env.productionにメモ
  username: <%= ENV["DATABASE_USERNAME"] %> # .env.productionにメモ
  password: <%= ENV["DATABASE_PASSWORD"] %> # .env.productionにメモ
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  charset: utf8
  collation: utf8_general_ci


